spring:
  profiles:
    active: default
  activiti:
     historyLevel: audit
  datasource:
     url: jdbc:postgresql://0.0.0.0:${it-database.port:5432}/photo-resub
     username: username
     password: password

timers:
#  notificationTimer: R/PT12S
  overallTimeout: PT2M